language: cpp
sudo: required
dist: trusty

compiler:
  - clang
  - gcc

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libtrace3-dev libpacketdump3-dev

install:
  - wget http://research.wand.net.nz/software/libflowmanager/libflowmanager-2.0.4.tar.gz
  - tar -xzvf libflowmanager-2.0.4.tar.gz
  - cd libflowmanager-2.0.4
  - ./configure
  - make
  - sudo make install
  - cd ..

script:
  - ./bootstrap.sh
  - ./configure
  - make
  - sudo make install

after_script:
  - ls -la
  - lpi_protoident
  - lpi_find_unknown
  - lpi_arff
